### ISSUE TITLE
there are a few problems/suggestions with this variant implementation

### ISSUE THREAD

**Issue by vkhomenko** [jarro2783/thenewcpp#1]
Hi,

I was unhappy with `boost::variant` (they support ancient compilers but fail on mainstream ones, and also severely limit the number of variant's types) and decided to switch to this implementation. Generally it worked, but I have a few suggestions and issues:

1. It would be nice to add a `static_visitor` template like in Boost, defining `result_type`, from which visitors are to be derived.

2. In `initialiser<...>::initialise(Variant& v, Current&& current)` there is a line
```
    v.construct(std::forward<Current>(current));
```
I believe it should be `std::move`?

3. Assignment of the form `visitor=element` fails to compile if the element's type is wrapped by `recursive_wrapper`. I managed to fix this by adding two new versions of `initialiser<...>::initialise` (hopefully a more elegant solution exists):
```
    template<typename Wrapped, typename Dummy=std::enable_if_t<std::is_same<Current,recursive_wrapper<Wrapped>>::value>>
    static void initialise(Variant& v, Wrapped&& current){ initialise(v,recursive_wrapper<Wrapped>(std::move(current))); }

    template<typename Wrapped, typename Dummy=std::enable_if_t<std::is_same<Current,recursive_wrapper<Wrapped>>::value>>
    static void initialise(Variant& v, const Wrapped& current){ initialise(v,recursive_wrapper<Wrapped>(current)); }
```

4. It would be nice to add a function `recover` that, given a reference to an element, would recover a reference to the enclosing variant. There is a strong motivation for this - one often needs to assign a new value to the variant from inside a visitor. I guess the implementation is easy as the address is the same (i.e. it is just a `reinterpret_cast<Var&>(element)`), where `Var` is provided as a template parameter. 

5. It would be nice to implement delayed visitation as in Boost - very useful and simple to do.

6. It would be nice to implement binary visitation as in Boost, but this might require some effort.

Cheers,
Victor Khomenko.

**Comment by jarro2783** [comment]
Everything mentioned here has now been addressed elsewhere.
