### ISSUE TITLE
Issues with binary visitation

### ISSUE THREAD

**Issue by mavam** [jarro2783/thenewcpp#12]
In f52dfe6ebc07632a4d618bbc2be945c1fb1a9c8b you fixed binary visitation, which I missed initially because in my small test program, I mistakenly used `apply_visitor`:

    Juice::Variant<int, double> v{42};
    Juice::Variant<int, double> w{4.2};
    Juice::apply_visitor(binary{}, v, w);

This compiled and executed for this visitor:

```
struct binary
{
  using result_type = void;

  template <typename T>
  void operator()(T const&, T const&) const
  {
    std::cout << "same" << std::endl;
  }

  template <typename T, typename U>
  void operator()(T const&, U const&) const
  {
    std::cout << "different" << std::endl;
  }
};
```

This is a pitfall which can lead to subtle bugs. The problem is that (right now) the signature of `apply_visitor` has a catch-all variadic argument `Args&&...` that does not get used any further. So the code compiled but the user gets unexpected behavior. How about making `apply_visitor` variadic, so that the number of arguments present after the visitor define the arity of `operator()` in the visitor? (We discussed this also in #7.) 

For example, this issue shows up as follows:

    Juice::apply_visitor(binary{}, v, w);
    w = 42;
    Juice::apply_visitor(binary{}, v, w);

This prints two times "different" although it should have been "different" and "same". Using `apply_visitor_binary` obviously yields the correct result.

**Comment by jarro2783** [comment]
I have neglected this code for a while. I am getting back into it for a bit, so we might see some progress here.

My problem is that it is very useful to pass arbitrary arguments to the visitor, hence the catch all Args...

I'm thinking of whether there is a way to allow both arbitrary arguments and an arbitrary number of variants. I think the ultimate would be something you could call with arguments and multiple variants and no extra syntax. It might work to match Visitable..., it just means that a variant can't be one of those remaining arguments (I don't even know if anyone would want that).

**Comment by mavam** [comment]
Meanwhile, the committee made [significant progress](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/#mailing2015-09) towards standardizing `std::variant`. If you plan on working on this code further, strategically it would make most sense to aim for a standard-compliant implementation. Herb conjectures that "`std::variant` will likely target the third revision of the Library Fundamentals TS."

**Comment by jarro2783** [comment]
I have fully implemented arbitrary arity visitation with arbitrary arguments. The variant at the moment is a superset of proposal P0088R0.
