### ISSUE TITLE
Missing `template` keyword on calls to apply_visitor and get

### ISSUE THREAD

**Issue by melak47** [jarro2783/thenewcpp#16]
Some calls to `variant::get` and `variant::apply_visitor` are missing the `template` keyword.
Clang 3.7.0 (mingw-w64-x86_64-clang++) refuses compilation without them:

    juice/variant.hpp:1144:18: error: use 'template' keyword to treat 'apply_visitor' as a dependent template name
    return var.apply_visitor<MPL::false_>(*this, std::forward<Args>(args)...);
               ^
               template

**Comment by jarro2783** [comment]
Fixed with the provided patch.
