### ISSUE TITLE
remove dependency on Visitor::result_type

### ISSUE THREAD

**Issue by vkhomenko** [jarro2783/thenewcpp#7]
The current code depends on every visitor having defined result_type. I believe this dependency can be easily eliminated using decltype or result_of. This would allow, e.g., passing the result of std::bind to apply_visitor.

**Comment by jarro2783** [comment]
The only problem with dropping result_type is that for Types... in the variant, each function Visitor::operator()(Types)... needs to return the same thing. There are several functions, not just one, and they all need to be consistent. It might be possible to do some sort of is_same and reject if they aren't.

**Comment by jarro2783** [comment]
This was easy with C++14 return type deduction. Done.
