### ISSUE TITLE
bug in recursive_wrapper move assignment

### ISSUE THREAD

**Issue by vkhomenko** [jarro2783/thenewcpp#9]
I believe recursive_wrapper::operator=(recursive_wrapper&&) has a bug. The current implementation is as follows:
```
recursive_wrapper& operator=(recursive_wrapper&& rhs){
    delete m_t;
    m_t = rhs.m_t;
    rhs.m_t = nullptr;
    return *this;
}
```
Note that if `lhs` is a sub-tree of `*this` then `delete m_t;` destroys `lhs` before it is moved. I think the correct code would be something like:
```
recursive_wrapper& operator=(recursive_wrapper&& rhs){
    if(this!=&rhs){
        T* const buf=m_t;
        m_t = rhs.m_t;
        rhs.m_t = nullptr;
        delete buf;
    }
    return *this;
}
```

**Comment by jarro2783** [comment]
This is now fixed.
